Covid 19 cases among passengers of international flight arriving at Japanese airports

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('cases_airport_jp.csv', index_col='id')
df

      case_id airport   date  age gender residence  history  symptom  year
id
1        3079      羽田   ６/27  40代     男性      神奈川県     キルギス      無症状  2021
2        3080      羽田   ６/26  10代     女性       東京都     イギリス   発熱、咽頭痛  2021
3        3081      羽田   ６/29  20代     女性       非公表     イギリス   発熱、咽頭痛  2021
4        3082      清水   ６/27  30代     男性       静岡県  アメリカ合衆国    咳嗽、頭痛  2021
5        3083      成田   ６/30  10代     男性       千葉県   インドネシア       発熱  2021
...       ...     ...    ...  ...    ...       ...      ...      ...   ...
1290     1889      成田  12/31  20代     女性       非公表  アメリカ合衆国      無症状  2021
1291     1890      成田  12/31  20代     男性       非公表  アメリカ合衆国      無症状  2021
1292     1891      羽田  12/31  50代     男性       非公表  アメリカ合衆国  嗅覚低下、咳嗽  2021
1293     1892      成田    1/1  20代     男性       宮城県   インドネシア      無症状  2021
1294     1893      成田    1/1  30代     男性      神奈川県   インドネシア      無症状  2021

[1294 rows x 9 columns]

In [3]:
# df.info()

Change the year of rows where the date is November or December to 2020.

In [4]:
# find rows where date is November or December
filt = (df['date'].str.startswith('12/')) | (df['date'].str.startswith('11/'))

# df.loc[filt]

# Change the year of these columns to 2020
df.loc[filt, ['year']] = 2020

In [5]:
# check if the year has been changed
df.loc[filt]

      case_id airport   date  age gender residence  history  symptom  year
id
1178     2006      羽田  12/29  40代     男性       宮城県     イギリス      無症状  2020
1230     1958      羽田  11/12  20代     男性       東京都  アメリカ合衆国       鼻汁  2020
1287     1886      成田  12/31  50代     女性       大阪府    フィリピン      無症状  2020
1288     1887      成田  12/31  40代     男性       長野県  アメリカ合衆国      無症状  2020
1289     1888      成田  12/31  20代     男性       非公表  アメリカ合衆国      無症状  2020
1290     1889      成田  12/31  20代     女性       非公表  アメリカ合衆国      無症状  2020
1291     1890      成田  12/31  20代     男性       非公表  アメリカ合衆国      無症状  2020
1292     1891      羽田  12/31  50代     男性       非公表  アメリカ合衆国  嗅覚低下、咳嗽  2020

In [6]:
# sort df by case_id
df = df.sort_values(by='case_id')

After checking the original report, case_id 307 is actually 3071.

Correct the case_id from 307 to 3071

In [7]:
filt = df['case_id'] == 307
df.loc[filt, ['case_id']] = 3071

In [8]:
df[df['case_id'] == 3071]

    case_id airport  date  age gender residence history symptom  year
id
21     3071      関空  ６/25  20代     男性       広島県    スペイン     無症状  2021

In [9]:
df.sort_values(by='case_id')

      case_id airport   date  age gender residence  history symptom  year
id
1287     1886      成田  12/31  50代     女性       大阪府    フィリピン     無症状  2020
1288     1887      成田  12/31  40代     男性       長野県  アメリカ合衆国     無症状  2020
1289     1888      成田  12/31  20代     男性       非公表  アメリカ合衆国     無症状  2020
1290     1889      成田  12/31  20代     女性       非公表  アメリカ合衆国     無症状  2020
1291     1890      成田  12/31  20代     男性       非公表  アメリカ合衆国     無症状  2020
...       ...     ...    ...  ...    ...       ...      ...     ...   ...
169      3173      羽田    ７/８  20代     男性       千葉県     スペイン     咽頭痛  2021
170      3174      成田    ７/８  20代     男性      神奈川県     スペイン     無症状  2021
171      3175      関空    ７/８  30代     男性       兵庫県    フィリピン     無症状  2021
172      3176      関空    ７/８  30代     男性       京都府   タジキスタン     無症状  2021
173      3177      関空    ７/８  50代     男性       大阪府    ミャンマー     無症状  2021

[1294 rows x 9 columns]

Change data in column 'date' to datetime

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1294 entries, 21 to 173
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   case_id    1294 non-null   int64
 1   airport    1294 non-null   object
 2   date       1294 non-null   object
 3   age        1294 non-null   object
 4   gender     1294 non-null   object
 5   residence  1294 non-null   object
 6   history    1294 non-null   object
 7   symptom    1294 non-null   object
 8   year       1294 non-null   int64
dtypes: int64(2), object(7)
memory usage: 101.1+ KB

In [11]:
# add year to the date
def combine_date_year(row):
    return row['date'] + '/' + str(row['year'])

In [12]:
df['date'] = df[['date', 'year']].apply(combine_date_year, axis=1)

In [13]:
df['date'] = pd.to_datetime(df['date'])

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1294 entries, 21 to 173
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   case_id    1294 non-null   int64
 1   airport    1294 non-null   object
 2   date       1294 non-null   datetime64[ns]
 3   age        1294 non-null   object
 4   gender     1294 non-null   object
 5   residence  1294 non-null   object
 6   history    1294 non-null   object
 7   symptom    1294 non-null   object
 8   year       1294 non-null   int64
dtypes: datetime64[ns](1), int64(2), object(6)
memory usage: 101.1+ KB

In [15]:
df = df.sort_values(by='date')

In [16]:
df.head()

      case_id airport       date  age gender residence  history symptom  year
id
1230     1958      羽田 2020-11-12  20代     男性       東京都  アメリカ合衆国      鼻汁  2020
1178     2006      羽田 2020-12-29  40代     男性       宮城県     イギリス     無症状  2020
1287     1886      成田 2020-12-31  50代     女性       大阪府    フィリピン     無症状  2020
1288     1887      成田 2020-12-31  40代     男性       長野県  アメリカ合衆国     無症状  2020
1289     1888      成田 2020-12-31  20代     男性       非公表  アメリカ合衆国     無症状  2020

Save cleaned data as csv

In [17]:
df.to_csv('cases_airport_jp_cleaned.csv')